import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ImagePlus, Save, Trash2 } from "lucide-react";
import type { Category, Product } from "@/types";

const inputClass = "focus-ring mt-2 min-h-12 w-full rounded-xl border border-ink/12 bg-white px-3.5 text-sm font-semibold placeholder:text-ink/30";
const labelClass = "text-xs font-extrabold uppercase tracking-[.11em] text-ink/56";

export function ProductForm({ categories, product, action, error }: { categories: Category[]; product?: Product | null; action: (formData: FormData) => Promise<void>; error?: string }) {
  return <form action={action} className="grid gap-6" encType="multipart/form-data">
    {error ? <p className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p> : null}
    <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/admin/productos" className="focus-ring inline-flex min-h-11 items-center gap-2 rounded-xl border border-ink/10 bg-white px-4 text-sm font-bold text-ink/65"><ArrowLeft size={17} /> Volver</Link><button type="submit" className="focus-ring inline-flex min-h-11 items-center gap-2 rounded-xl bg-ink px-5 text-sm font-extrabold text-white"><Save size={17} /> {product ? "Guardar cambios" : "Crear producto"}</button></div>
    <section className="rounded-[1.4rem] border border-ink/8 bg-white p-5 sm:p-7"><h2 className="font-display text-2xl">Información principal</h2><div className="mt-6 grid gap-5 sm:grid-cols-2">
      <label className={`${labelClass} sm:col-span-2`}>Nombre *<input name="name" defaultValue={product?.name} required className={inputClass} placeholder="Ej. Termo simil STL 1.2L" /></label>
      <label className={labelClass}>Slug<input name="slug" defaultValue={product?.slug} className={inputClass} placeholder="Se genera automáticamente" /></label>
      <label className={labelClass}>SKU opcional<input name="sku" defaultValue={product?.sku || ""} className={inputClass} placeholder="Código del proveedor" /></label>
      <label className={labelClass}>Categoría *<select name="category_id" defaultValue={product?.category_id || ""} required className={inputClass}><option value="" disabled>Elegir categoría</option>{categories.filter((category) => category.slug !== "ofertas").map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label>
      <label className={`${labelClass} sm:col-span-2`}>Descripción corta *<textarea name="short_description" defaultValue={product?.short_description} required rows={2} className={`${inputClass} py-3`} placeholder="Una frase clara para las tarjetas y buscadores." /></label>
      <label className={`${labelClass} sm:col-span-2`}>Descripción completa *<textarea name="description" defaultValue={product?.description} required rows={6} className={`${inputClass} py-3`} placeholder="Contá qué incluye, para quién sirve y sus ventajas." /></label>
    </div></section>
    <section className="rounded-[1.4rem] border border-ink/8 bg-white p-5 sm:p-7"><h2 className="font-display text-2xl">Precio y disponibilidad</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
      <label className={labelClass}>Precio contado *<input type="number" name="price" min="0" defaultValue={product?.price} required className={inputClass} /></label>
      <label className={labelClass}>Precio anterior<input type="number" name="previous_price" min="0" defaultValue={product?.previous_price || ""} className={inputClass} /></label>
      <label className={labelClass}>Cantidad de cuotas<input type="number" name="installments" min="1" defaultValue={product?.installments || ""} className={inputClass} /></label>
      <label className={labelClass}>Precio por cuota<input type="number" name="installment_price" min="0" defaultValue={product?.installment_price || ""} className={inputClass} /></label>
      <label className={labelClass}>Stock opcional<input type="number" name="stock" min="0" defaultValue={product?.stock ?? ""} className={inputClass} /></label>
      <label className={labelClass}>Estado *<select name="status" defaultValue={product?.status || "available"} className={inputClass}><option value="available">Disponible</option><option value="last_units">Últimas unidades</option><option value="sold_out">Agotado</option><option value="coming_soon">Próximamente</option><option value="hidden">Oculto</option><option value="archived">Archivado</option></select></label>
    </div><div className="mt-6 flex flex-wrap gap-3">{[["featured", "Destacado", product?.featured], ["offer", "Oferta", product?.offer], ["is_new", "Nuevo", product?.is_new]].map(([name, label, checked]) => <label key={String(name)} className="flex min-h-11 cursor-pointer items-center gap-2 rounded-xl bg-cream px-4 text-sm font-bold"><input type="checkbox" name={String(name)} defaultChecked={Boolean(checked)} className="size-4 accent-clay" />{String(label)}</label>)}</div></section>
    <section className="rounded-[1.4rem] border border-ink/8 bg-white p-5 sm:p-7"><h2 className="font-display text-2xl">Contenido del producto</h2><div className="mt-6 grid gap-5 sm:grid-cols-2">
      <label className={labelClass}>Etiquetas<textarea name="tags" defaultValue={product?.tags.join(", ")} rows={5} className={`${inputClass} py-3`} placeholder="termo, mate, regalo, personalizado" /><span className="mt-2 block normal-case tracking-normal text-ink/42">Separalas con comas. Ayudan al buscador.</span></label>
      <label className={labelClass}>Características<textarea name="features" defaultValue={product?.features.join("\n")} rows={5} className={`${inputClass} py-3`} placeholder={"Capacidad 1.2 litros\nMate incluido\nEntrega rápida"} /><span className="mt-2 block normal-case tracking-normal text-ink/42">Una característica por línea.</span></label>
    </div></section>
    <section className="rounded-[1.4rem] border border-ink/8 bg-white p-5 sm:p-7"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-sage text-forest"><ImagePlus size={20} /></span><div><h2 className="font-display text-2xl">Imágenes</h2><p className="text-xs text-ink/48">JPG, PNG o WebP. Podés elegir varias.</p></div></div>
      {product?.images.length ? <div className="mt-5"><p className="mb-3 text-xs font-bold text-ink/48">Para reemplazar una imagen, marcala para quitar y elegí la nueva antes de guardar.</p><div className="flex gap-3 overflow-x-auto pb-2">{product.images.map((image, index) => <label key={image.id || image.image_url} className="group w-28 shrink-0 cursor-pointer rounded-xl border border-ink/10 bg-cream p-1.5"><span className="relative block aspect-square overflow-hidden rounded-lg bg-white"><Image src={image.image_url} alt={`Imagen actual ${index + 1}`} fill sizes="112px" className="object-cover" /></span>{image.id ? <span className="mt-2 flex min-h-9 items-center justify-center gap-1.5 rounded-lg px-2 text-xs font-extrabold text-red-700 transition group-has-[:checked]:bg-red-100"><input type="checkbox" name="delete_image_ids" value={image.id} className="size-4 accent-red-700" /><Trash2 size={14} aria-hidden="true" /> Quitar</span> : null}</label>)}</div></div> : null}
      <label className="focus-ring mt-5 flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-ink/14 bg-cream/60 px-4 text-center text-sm font-bold text-ink/55 hover:border-clay/35"><ImagePlus size={22} className="mb-2 text-clay" />{product ? "Agregar nuevas imágenes" : "Seleccionar imágenes"}<input type="file" name="images" accept="image/jpeg,image/png,image/webp" multiple className="mt-3 max-w-full text-xs" /></label>
    </section>
    <div className="flex justify-end"><button type="submit" className="focus-ring inline-flex min-h-12 items-center gap-2 rounded-xl bg-ink px-6 text-sm font-extrabold text-white"><Save size={17} /> {product ? "Guardar cambios" : "Crear producto"}</button></div>
  </form>;
}
