import Link from "next/link";
import { ArrowRight, Bot, CheckCircle2, LayoutDashboard, MessageSquareText, ShieldCheck, ShoppingBag, Sparkles, Zap } from "lucide-react";

export const metadata = { title: "ORQELIS | Comercio digital administrado con IA", description: "Tienda online, panel de administración y un asistente de IA que ejecuta tareas sobre tu negocio." };

const commands = ["Subí este producto a $55.000 y dejalo destacado.", "Actualizá el stock y poné estos productos en oferta.", "Agregales características y mejorá las descripciones.", "Dejá solamente estos productos publicados."];

export default function HomePage() {
  return <main className="bg-paper text-ink">
    <section className="relative overflow-hidden border-b border-ink/10 bg-cream"><div className="container-store grid min-h-[78vh] items-center gap-12 py-20 lg:grid-cols-[1.05fr_.95fr] lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-clay/20 bg-white px-4 py-2 text-xs font-black uppercase tracking-[.16em] text-clay"><Sparkles size={15}/> Comercio digital + IA</div><h1 className="font-display mt-7 max-w-4xl text-5xl leading-[.98] sm:text-6xl lg:text-7xl">Pedís.<br/><span className="text-clay">ORQELIS lo hace.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-ink/65">Una plataforma para comercios que combina tienda online, administración y un asistente de inteligencia artificial capaz de ejecutar tareas sobre tu catálogo con instrucciones simples.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/demo" className="inline-flex min-h-13 items-center gap-2 rounded-xl bg-ink px-6 py-4 text-sm font-extrabold text-white">Ver demo de la tienda <ArrowRight size={18}/></Link><a href="#como-funciona" className="inline-flex min-h-13 items-center gap-2 rounded-xl border border-ink/15 bg-white px-6 py-4 text-sm font-extrabold">Cómo funciona</a></div><p className="mt-5 text-sm text-ink/45">Menos tiempo administrando. Más tiempo vendiendo.</p></div><div className="rounded-[2rem] border border-ink/10 bg-white p-5 shadow-2xl shadow-ink/10 sm:p-7"><div className="flex items-center justify-between border-b border-ink/10 pb-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-clay">ORQELIS AI</p><p className="mt-1 font-extrabold">Asistente del negocio</p></div><span className="grid size-11 place-items-center rounded-2xl bg-clay text-white"><Bot size={23}/></span></div><div className="space-y-4 py-6"><div className="ml-auto max-w-[88%] rounded-2xl rounded-br-md bg-ink p-4 text-sm leading-6 text-white">Subí este producto. Cuesta $55.000, tengo 5 unidades y quiero que aparezca destacado.</div><div className="max-w-[88%] rounded-2xl rounded-bl-md bg-sand/55 p-4 text-sm leading-6"><div className="mb-2 flex items-center gap-2 font-extrabold text-clay"><CheckCircle2 size={17}/> Listo</div>Producto preparado, organizado y publicado en la tienda.</div></div><div className="grid grid-cols-3 gap-2 border-t border-ink/10 pt-4 text-center text-[11px] font-extrabold"><span className="rounded-xl bg-cream p-3">Producto ✓</span><span className="rounded-xl bg-cream p-3">Stock ✓</span><span className="rounded-xl bg-cream p-3">Destacado ✓</span></div></div></div></section>

    <section className="container-store py-20 sm:py-28"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-clay">Un sistema, tres piezas</p><h2 className="font-display mt-3 text-4xl sm:text-5xl">Todo lo que el comercio necesita</h2><p className="mt-4 text-ink/60">ORQELIS no es solamente una tienda. Es la infraestructura para vender y mantener el negocio actualizado.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[[ShoppingBag,"ORQELIS Store","Una tienda profesional para que tus clientes exploren productos, ofertas y compren desde cualquier dispositivo."],[LayoutDashboard,"ORQELIS Admin","Controlá catálogo, imágenes, categorías, precios, stock, destacados y promociones sin tocar código."],[Bot,"ORQELIS AI","Dale instrucciones en lenguaje natural y delegá tareas repetitivas de administración del catálogo."]].map(([Icon,title,text]) => { const I=Icon as typeof ShoppingBag; return <article key={String(title)} className="rounded-[1.75rem] border border-ink/10 bg-white p-7"><span className="grid size-12 place-items-center rounded-2xl bg-sand/55 text-clay"><I size={23}/></span><h3 className="font-display mt-6 text-2xl">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-ink/60">{String(text)}</p></article>})}</div></section>

    <section id="como-funciona" className="bg-forest py-20 text-white sm:py-28"><div className="container-store grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-sand">La diferencia está en pedir</p><h2 className="font-display mt-3 text-4xl sm:text-5xl">Administrar sin hacer todo manualmente.</h2><p className="mt-5 max-w-xl leading-7 text-white/65">En lugar de entrar a múltiples formularios para cada cambio, ORQELIS AI convierte una instrucción en acciones concretas sobre el sistema.</p><div className="mt-8 grid gap-3">{commands.map((command)=><div key={command} className="flex gap-3 rounded-2xl bg-white/8 p-4"><MessageSquareText className="mt-0.5 shrink-0 text-sand" size={19}/><span className="text-sm text-white/85">“{command}”</span></div>)}</div></div><div className="rounded-[2rem] bg-white p-7 text-ink"><p className="text-xs font-black uppercase tracking-[.18em] text-clay">Flujo ORQELIS</p>{[["01","Pedís","Escribís lo que necesitás en lenguaje natural."],["02","La IA interpreta","Identifica productos, cambios y datos necesarios."],["03","ORQELIS ejecuta","Actualiza el sistema respetando permisos y validaciones."],["04","Tu tienda queda lista","Los cambios se reflejan en la experiencia del cliente."]].map(([n,t,d])=><div key={n} className="grid grid-cols-[42px_1fr] gap-4 border-b border-ink/10 py-5 last:border-0"><span className="font-display text-2xl text-clay">{n}</span><div><p className="font-extrabold">{t}</p><p className="mt-1 text-sm text-ink/55">{d}</p></div></div>)}</div></div></section>

    <section className="container-store py-20 sm:py-28"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[[Zap,"Menos trabajo operativo","Automatizá tareas repetitivas del catálogo."],[ShieldCheck,"Control y seguridad","Acciones sensibles pueden requerir confirmación."],[Sparkles,"Contenido asistido","Descripciones y características mejor organizadas."],[ShoppingBag,"Adaptable a tu marca","Identidad, catálogo y operación de cada comercio."]].map(([Icon,t,d])=>{const I=Icon as typeof Zap;return <div key={String(t)} className="rounded-2xl bg-cream p-6"><I className="text-clay"/><p className="mt-4 font-extrabold">{String(t)}</p><p className="mt-2 text-sm leading-6 text-ink/55">{String(d)}</p></div>})}</div></section>

    <section id="contacto" className="container-store pb-24"><div className="overflow-hidden rounded-[2.25rem] bg-clay px-7 py-12 text-white sm:px-12 lg:flex lg:items-center lg:justify-between lg:gap-10"><div><p className="text-xs font-black uppercase tracking-[.2em] text-sand">ORQELIS para comercios</p><h2 className="font-display mt-3 text-4xl sm:text-5xl">¿Qué le delegarías primero a la IA?</h2><p className="mt-4 max-w-2xl text-white/75">Estamos preparando ORQELIS para implementarlo en distintos negocios con su propia identidad, catálogo y configuración.</p></div><div className="mt-8 flex shrink-0 flex-wrap gap-3 lg:mt-0"><Link href="/demo" className="inline-flex items-center gap-2 rounded-xl bg-white px-6 py-4 text-sm font-extrabold text-ink">Probar la demo <ArrowRight size={18}/></Link></div></div></section>
  </main>;
}
