import { Save } from "lucide-react";
import { updateSettingsAction } from "@/app/admin/actions";
import { getSiteSettings } from "@/services/settings";

const inputClass = "focus-ring mt-2 min-h-12 w-full rounded-xl border border-ink/12 bg-white px-3.5 text-sm font-semibold placeholder:text-ink/30";
const labelClass = "text-xs font-extrabold uppercase tracking-[.11em] text-ink/56";
type Props = { searchParams: Promise<{ success?: string }> };

export default async function AdminSettingsPage({ searchParams }: Props) {
  const [settings, query] = await Promise.all([getSiteSettings(), searchParams]);
  return <div><div><p className="text-xs font-black uppercase tracking-[.16em] text-clay">Datos comerciales</p><h1 className="font-display mt-2 text-4xl">Configuración</h1><p className="mt-2 text-sm text-ink/48">Estos datos se usan en toda la tienda y sus enlaces de contacto.</p></div>{query.success ? <p className="mt-5 rounded-xl bg-green-50 p-4 text-sm font-bold text-green-800">Configuración guardada correctamente.</p> : null}<form action={updateSettingsAction} className="mt-7 grid gap-5"><section className="rounded-[1.4rem] border border-ink/8 bg-white p-5 sm:p-7"><h2 className="font-display text-2xl">Identidad y contacto</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className={labelClass}>Nombre de tienda *<input name="store_name" defaultValue={settings.storeName} required className={inputClass} /></label><label className={labelClass}>Email opcional<input type="email" name="email" defaultValue={settings.email} className={inputClass} placeholder="ventas@tutienda.com" /></label><label className={labelClass}>WhatsApp *<input name="whatsapp_number" defaultValue={settings.whatsappNumber} required className={inputClass} placeholder="54911XXXXXXXX" /><span className="mt-2 block normal-case tracking-normal text-ink/42">Solo números, con código de país y área.</span></label><label className={labelClass}>Instagram *<input type="url" name="instagram_url" defaultValue={settings.instagramUrl} required className={inputClass} placeholder="https://instagram.com/usuario" /></label></div></section><section className="rounded-[1.4rem] border border-ink/8 bg-white p-5 sm:p-7"><h2 className="font-display text-2xl">Entregas y envíos</h2><div className="mt-6 grid gap-5"><label className={labelClass}>Texto de envíos<textarea name="shipping_text" defaultValue={settings.shippingText} rows={4} className={`${inputClass} py-3`} /></label><label className={labelClass}>Texto de entregas<textarea name="delivery_text" defaultValue={settings.deliveryText} rows={4} className={`${inputClass} py-3`} /></label></div></section><div className="flex justify-end"><button className="focus-ring inline-flex min-h-12 items-center gap-2 rounded-xl bg-ink px-6 text-sm font-extrabold text-white"><Save size={17} /> Guardar configuración</button></div></form></div>;
}
