import { Plus, Save, Trash2 } from "lucide-react";
import { createCategoryAction, deleteCategoryAction, updateCategoryAction } from "@/app/admin/actions";
import { getCategories } from "@/services/catalog";

const inputClass = "focus-ring min-h-11 w-full rounded-xl border border-ink/10 bg-white px-3 text-sm font-semibold";
const icons = ["Package", "Blender", "Headphones", "CookingPot", "House", "CupSoda", "Sparkles", "BadgePercent"];

export default async function AdminCategoriesPage() {
  const categories = await getCategories();
  return <div><div><p className="text-xs font-black uppercase tracking-[.16em] text-clay">Organización</p><h1 className="font-display mt-2 text-4xl">Categorías</h1><p className="mt-2 text-sm text-ink/48">Ordená el catálogo para que tus clientes encuentren rápido lo que buscan.</p></div><section className="mt-7 rounded-[1.4rem] border border-ink/8 bg-white p-5 sm:p-7"><h2 className="font-display text-2xl">Nueva categoría</h2><form action={createCategoryAction} className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_.7fr_auto]"><input name="name" required placeholder="Nombre" aria-label="Nombre" className={inputClass} /><input name="slug" placeholder="Slug automático" aria-label="Slug" className={inputClass} /><select name="icon" aria-label="Icono" className={inputClass}>{icons.map((icon) => <option key={icon} value={icon}>{icon}</option>)}</select><button className="focus-ring inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-ink px-4 text-sm font-extrabold text-white"><Plus size={16} /> Agregar</button></form></section><section className="mt-5 overflow-hidden rounded-[1.4rem] border border-ink/8 bg-white"><div className="border-b border-ink/8 bg-[#f8f6f2] px-5 py-3 text-[.64rem] font-black uppercase tracking-wider text-ink/44">Categorías existentes</div><div className="divide-y divide-ink/8">{categories.map((category) => <div key={category.id} className="p-4 sm:p-5"><form action={updateCategoryAction.bind(null, category.id)} className="grid gap-3 sm:grid-cols-[1fr_1fr_.7fr_auto]"><input name="name" defaultValue={category.name} required aria-label={`Nombre de ${category.name}`} className={inputClass} /><input name="slug" defaultValue={category.slug} required aria-label={`Slug de ${category.name}`} className={inputClass} /><select name="icon" defaultValue={category.icon} aria-label={`Icono de ${category.name}`} className={inputClass}>{icons.map((icon) => <option key={icon} value={icon}>{icon}</option>)}</select><div className="flex gap-2"><button className="focus-ring inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl border border-ink/10 px-3 text-xs font-extrabold"><Save size={15} /> Guardar</button><button formAction={deleteCategoryAction.bind(null, category.id)} className="focus-ring grid size-11 place-items-center rounded-xl border border-red-200 text-red-600" title="Eliminar categoría"><Trash2 size={15} /></button></div></form><p className="mt-2 text-xs font-bold text-ink/35">{category.product_count || 0} productos</p></div>)}</div></section></div>;
}
